### ISSUE TITLE
where the lanceDb created or exist 

### ISSUE THREAD

**Issue by abdullah-4Mohammed** [giusedroid/serverless-embeddings-lancedb-bedrock#3]
Hi, 
 I am in the test step and I am facing this error "Table 'doc_table' was not found". I just noticed that the sam template dosent create any table and I dont know where the db should be? thanks. 
 
 bash 20-query.sh chatbot-rag ./events/prompt.json
from nodejs script bucket, table, prompt, region
chatbot-rag-us-east-1-767397720274
doc_table
./events/prompt.json
us-east-1
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Table 'doc_table' was not found]

Node.js v18.17.1

**Comment by abdullah-4Mohammed** [comment]
well I see the code trying to create it in the S3 but there is no table been created there.

**Comment by AhmedX6** [comment]
How did you fix this ?  @abdullah-4Mohammed
